### ISSUE TITLE
ocsort_dance_model.pth.tar

### ISSUE THREAD

**Issue by GeeniTiming** [zyayoung/ByteTrackInference#1]
Hello,when I run bash inference.sh,there is an error says that FileNotFoundError: [Errno 2] No such file or directory: 'ocsort_dance_model.pth.tar'.So how I can get the pth.tar file?Looking forward to your reply.

**Comment by zyayoung** [comment]
It can be found here https://github.com/noahcao/OC_SORT/blob/master/docs/MODEL_ZOO.md
