### ISSUE TITLE
how to solve .grad problem

### ISSUE THREAD

**Issue by Bajrangi97** [zyayoung/ByteTrackInference#2]
Warning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)

**Comment by mpilligua** [comment]
Hello, I'm having the same issue. How did you solve it?
